"""T and X learners with Qini, uplift and policy value on randomized holdouts; PEHE and quadrants on the simulator."""

from marginal_targeting.learners import (
    LearnerParams,
    SureThingsPolicy,
    TLearner,
    XLearner,
    feature_matrix,
    split_customers,
)
from marginal_targeting.metrics import (
    QiniBootstrap,
    QiniDifference,
    choose_share,
    chosen_on,
    contact_mask,
    interior_test,
    oracle_regret,
    paired_bootstrap_qini,
    pehe,
    policy_value_curve,
    qini_coefficient,
    qini_curve,
    quadrant_shares_contacted,
    uplift_curve,
    uplift_top_decile,
)
from marginal_targeting.protocol import (
    LEARNERS,
    SHARE_GRID,
    InteriorCheck,
    PolicyResult,
    PolicyValuePoint,
    ProtocolResult,
    ProtocolSettings,
    SplitRows,
    run_protocol,
)

__all__ = [
    "LEARNERS",
    "SHARE_GRID",
    "InteriorCheck",
    "LearnerParams",
    "PolicyResult",
    "PolicyValuePoint",
    "ProtocolResult",
    "ProtocolSettings",
    "QiniBootstrap",
    "QiniDifference",
    "SplitRows",
    "SureThingsPolicy",
    "TLearner",
    "XLearner",
    "choose_share",
    "chosen_on",
    "contact_mask",
    "feature_matrix",
    "interior_test",
    "oracle_regret",
    "paired_bootstrap_qini",
    "pehe",
    "policy_value_curve",
    "qini_coefficient",
    "qini_curve",
    "quadrant_shares_contacted",
    "run_protocol",
    "split_customers",
    "uplift_curve",
    "uplift_top_decile",
]
